### ISSUE TITLE
New release with latest fixes

### ISSUE THREAD

**Issue by luiscastilho** [eshta/toute#6]
Can you create a new release (maybe 1.1.1) with the latest fixes?
This way I can use toute in an environment with Elasticsearch 5.6.

**Comment by 0mars** [comment]
Release Notes(NEWS):
- Elasticsearch 5.6.x compat
- Add Short Field
- Add Double Field 

How does that look to you ?

**Comment by luiscastilho** [comment]
Perfect! :+1:

**Comment by luiscastilho** [comment]
Friendly ping just because I'm really needing this new version. :sweat_smile:

**Comment by 0mars** [comment]
the tests are still failing

**Comment by 0mars** [comment]
@luiscastilho released 🥳
